### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by rogerallen** [Jacajack/stm32-faust-synth#1]
Hi there,

I'm trying to build this to try to get it running on my STM32F407VG Discovery board.  Eventually, I think I'll need to know how to adjust the firmware for loading on my board, but first, I just need to compile it & I'm having troubles.

System: Ubuntu 20.04
gcc path from STM32CubeIDE install: /opt/st/stm32cubeide_1.6.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.linux64_1.5.0.202011040924/tools/bin
FAUST Version 2.32.16 (just installed from git source build)

I've uploaded the make.log to gist here: https://gist.github.com/rogerallen/c5ab4c61c573cbb084523da6979b7d1e

And I think this is the first error:

```
In file included from synth.cpp:23:
./faust/panel.hpp: In member function 'virtual faust_dsp_panel* faust_dsp_panel::clone()':
./faust/panel.hpp:391:30: error: invalid new-expression of abstract class type 'faust_dsp_panel'
  391 |   return new faust_dsp_panel();
      |                              ^
./faust/panel.hpp:27:7: note:   because the following virtual functions are pure within 'faust_dsp_panel':
   27 | class faust_dsp_panel : public faust_dsp_base {
      |       ^~~~~~~~~~~~~~~
```
Thanks in advance for any help you can give.  This looks like a neat project.

**Comment by Jacajack** [comment]
Hi,

It seems that Faust has changed its DSP base class interface since 2.30.5 (the version I had installed). I can reproduce your error after installing the newest version. Apparently `getInputSampleRate()` and `getOutputSampleRate()` are no longer generated. This can be fixed with replacing the pure virtual declarations in `faust_dsp_base` with:
```cpp
virtual int getInputRate(int channel) {return getSampleRate();}
virtual int getOutputRate(int channel) {return getSampleRate();}
```
This should work for both old and new Faust versions. Funnily enough, these functions aren't even used by the synthesizer code.

If you have any further questions, please don't hesitate to ask :)

**Comment by rogerallen** [comment]
Great, that fixed the compile!

The elf doesn't seem to work on my board, but I'll keep debugging.  Thanks!

**Comment by Jacajack** [comment]
@rogerallen If you want to get this code to run on the Discovery board, you'll have to make quite a lot of changes, because I was working with a custom PCB (with a different audio codec and analog multiplexers for reading a total of 36 analog inputs). I have a feeling that there are more differences than similarities. You might be better off by just taking the Faust-related code from here and integrating with what you have already. The DSP base class seems to be pretty portable. Just a couple of things too:

 - If I were writing this for the second time, I probably would completely redo this overengineered MIDI interpreter. If you're looking for a simple C implementation supporting all the basic MIDI messages (CCs might be useful if you want to control the DSP parameters!), you'll find a much better one here: https://github.com/Jacajack/usynth/blob/master/src/midi.h
 - My code uses Faust DSP controls metadata to link analog inputs to specific DSP parameters. It's not very pretty, but you can find the bit of code responsible for that [here](https://github.com/Jacajack/stm32-faust-synth/blob/master/synth.cpp#L55-L110). You might need something similar if you decide to use MIDI CCs to control the DSP.
 - [fast_math.hpp](https://github.com/Jacajack/stm32-faust-synth/blob/master/fast_math.hpp) is my custom implementation of fast math functions and it's not complete. If you're unlucky, your DSP might use some missing function. In such case, you will have to implement one yourself (or at least forward the call to some function from `<cmath>`). I remember that I once saw a complete optimized implementation of math.h somewhere in the Faust repo, but sadly I can no longer find it.

I hope this helps!

**Comment by rogerallen** [comment]
Ah, thanks for the info.  That does suggest a different approach.  I'll take a look more closely at the Faust code and how to use it.  I think I might want to have it output C instead of C++ for my own purposes.

**Comment by Jacajack** [comment]
No problem. Be sure to try their online IDE at https://faustide.grame.fr/. It's really great for learning and prototyping
